name: genie_client_dart
version: 0.1.1
description: A dart client for the genie_api project
authors:
  - Author <author@homepage>
homepage: homepage
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: '>=0.12.0 <0.13.0'
dev_dependencies:
  test: ^1.3.0
