name: genie_client_dart
version: 0.1.9
description: A dart client for the genie_api project
authors:
  - Brandan Schmitz <brandan.schmitz@celestialdata.net>
homepage: https://github.com/brandan-schmitz/genie_client_dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: '>=0.12.0 <0.13.0'
dev_dependencies:
  test: ^1.3.0
