name: makerspacegenie_client_dart
version: 0.1.0
description: A Dart API Client for the Makerspace Genie API project.
authors:
  - Author <author@homepage>
homepage: homepage
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: '>=0.12.0 <0.13.0'
dev_dependencies:
  test: ^1.3.0
